services:
  db:
    restart: always
    image: postgres:latest
    container_name: javapg
    ports:
      - 5438:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"